# Generated by Django 3.0.8 on 2020-07-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstoreName', models.CharField(max_length=20, verbose_name='서점 이름')),
                ('bookstoreExp', models.TextField(verbose_name='서점 정보')),
                ('bookstoreAddress', models.CharField(max_length=200, verbose_name='서점 주소')),
                ('bookstoreTel', models.CharField(blank=True, max_length=30, verbose_name='서점 연락처')),
                ('bookstorePic', models.ImageField(blank=True, upload_to='bookstore/%Y/%m/%d', verbose_name='서점 이미지')),
            ],
        ),
    ]
