# Generated by Django 3.0.8 on 2020-07-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=30, verbose_name='포스트제목')),
                ('postExp', models.TextField(verbose_name='포스트내용')),
                ('postDate', models.DateField(auto_now_add=True, verbose_name='포스트등록날짜')),
                ('postPic', models.ImageField(blank=True, null=True, upload_to='writerblogs/postPic', verbose_name='포스트사진')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
